# Tutorial
Going through the Julia tutorial on juliaacademy.com.

## Variables and Printing

In [1]:
println("Hello World")

Hello World


In [3]:
# one-line comment
#= multi-
line
comment =#

pi = 3.1415
println(pi)
println(typeof(pi))

pi = "Pie"

println(pi)
println(typeof(pi))

3.1415
Float64
Pie
String


## Strings

In [7]:
s1 = "I am a string."
s2 = """I am also a "string"."""

# single quotation marks denote a char, not a string
typeof('a')

Char

In [9]:
#= a $-sign can be used to insert other variables into a string,
or evaluate expressions within a string =#

name = "Leo"
num_fingers = 10
num_toes = 10

println("Hello, my name is $name. I have $(num_fingers+num_toes) digits.")

Hello, my name is Leo. I have 20 appendages.


In [12]:
# There are muliple ways to concatenate strings

println(string("I have ", 10, " digits."))
println("I have 10"*" digits.")

I have 10 digits.
I have 10 digits.


## Data Structures

In [20]:
# setting up a dictionary
mydict = Dict("Jenny" => 123, "James" => 456)
mydict["Juan"] = 789

# deleting a specific value
pop!(mydict, "Jenny")
mydict

# calling dicts has to be done by key, as they are unordered, positional indexing will not work

Dict{String,Int64} with 2 entries:
  "James" => 456
  "Juan"  => 789

In [24]:
# setting up a tuple, julia is 1-indexed
mytuple = ("a", "b", "c")
mytuple[1]

# tuples are immutable, updating only works via re-definition

"b"

In [38]:
# setting up an array, they are mutable and ordered, they can be mixed
myarray = ["a", "b", "c"]
myotherarray = [1,2,3]
mymixedarray = ["a", 2, 'c']

mymixedarray[3] = "cstring"

# items can be added and removed at the end of the array with push! and pop!
pop!(mymixedarray)
push!(mymixedarray, "pushedcstring")

#= arrays can have arbitrarily many dimensions and contain 
any combination elementary and composite data types =#
mynestedarray = [[1, 2, 3], ["1", "2", "3"], [1, "2", '3']]

# there are many functions to initialise certain array structures 
myrandarray = rand(4, 3, 2)

4×3×2 Array{Float64,3}:
[:, :, 1] =
 0.465985  0.966172   0.135929
 0.414777  0.0558579  0.178605
 0.441664  0.430494   0.766781
 0.828035  0.788755   0.98392

[:, :, 2] =
 0.723536   0.516805  0.473345
 0.688645   0.60558   0.200878
 0.440649   0.252553  0.223645
 0.0113139  0.809792  0.657483

## Loops

In [53]:
# Julia supports while-loops
alphabet = ["A", "B", "C"]

i = 1
while i <= length(alphabet)
    println("The current letter is $(alphabet[i])")
    i += 1
end

println("")

# and for-loops

for letter in alphabet
    println("The current letter is $letter")
end

# both loop types can be nested
m, n = 5, 5
A = zeros(m, n)

for i in 1:m, j in 1:n
        A[i, j] = i + j
end

# but typically nested loops are better expressed through array comprehensions 
B = [i + j for i in 1:m, j in 1:n]

# it is also possible to nest comprehensions in for loops

for n in 1:10
    C = [i + j for i in 1:n, j in 1:n]
    display(C)
end

1×1 Array{Int64,2}:
 2

2×2 Array{Int64,2}:
 2  3
 3  4

3×3 Array{Int64,2}:
 2  3  4
 3  4  5
 4  5  6

4×4 Array{Int64,2}:
 2  3  4  5
 3  4  5  6
 4  5  6  7
 5  6  7  8

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

6×6 Array{Int64,2}:
 2  3  4   5   6   7
 3  4  5   6   7   8
 4  5  6   7   8   9
 5  6  7   8   9  10
 6  7  8   9  10  11
 7  8  9  10  11  12

7×7 Array{Int64,2}:
 2  3   4   5   6   7   8
 3  4   5   6   7   8   9
 4  5   6   7   8   9  10
 5  6   7   8   9  10  11
 6  7   8   9  10  11  12
 7  8   9  10  11  12  13
 8  9  10  11  12  13  14

8×8 Array{Int64,2}:
 2   3   4   5   6   7   8   9
 3   4   5   6   7   8   9  10
 4   5   6   7   8   9  10  11
 5   6   7   8   9  10  11  12
 6   7   8   9  10  11  12  13
 7   8   9  10  11  12  13  14
 8   9  10  11  12  13  14  15
 9  10  11  12  13  14  15  16

9×9 Array{Int64,2}:
  2   3   4   5   6   7   8   9  10
  3   4   5   6   7   8   9  10  11
  4   5   6   7   8   9  10  11  12
  5   6   7   8   9  10  11  12  13
  6   7   8   9  10  11  12  13  14
  7   8   9  10  11  12  13  14  15
  8   9  10  11  12  13  14  15  16
  9  10  11  12  13  14  15  16  17
 10  11  12  13  14  15  16  17  18

10×10 Array{Int64,2}:
  2   3   4   5   6   7   8   9  10  11
  3   4   5   6   7   8   9  10  11  12
  4   5   6   7   8   9  10  11  12  13
  5   6   7   8   9  10  11  12  13  14
  6   7   8   9  10  11  12  13  14  15
  7   8   9  10  11  12  13  14  15  16
  8   9  10  11  12  13  14  15  16  17
  9  10  11  12  13  14  15  16  17  18
 10  11  12  13  14  15  16  17  18  19
 11  12  13  14  15  16  17  18  19  20

The current letter is A
The current letter is B
The current letter is C

The current letter is A
The current letter is B
The current letter is C


## Conditionals

In [60]:
# conditional statements mirror Python syntax
x = 1
y = 2

if x > y
    x
else
    y
end

# less verbosely, one can also use a ternaty operator
(x > y) ? x : y
    
# one can also play with the AND operators sequential evaluation
(x > y) && println(x)
(x < y) && println(y)

2


## Functions